#!/bin/bash
set -euo pipefail

# Create ephemeral devbox user with host UID/GID so host volumes can be accessed
groupadd --gid "$DEVBOX_GID" devbox
useradd --uid "$DEVBOX_UID" --gid "$DEVBOX_GID" devbox

# Create runtime dirs that don't exist yet
d=(
  /run/apache2/devbox-vhosts
  /run/mysqld
  /run/php
  /var/log/apache2
  /var/log/mysql
)
install -m 755 -d "${d[@]}"

# Ensure devbox user can access everything it needs
d=(
  /etc/service
  /home/devbox
  /run
  /var/lib/mysql
  /var/lock
  /var/log
)
chown --recursive devbox:devbox "${d[@]}"

cat <<EOF

  MEN AT WORK Devbox $(cat /etc/devbox/version)

  Dashboard:    http://devbox.localhost
  Mailcatcher:  http://mailcatcher.devbox.localhost

  MariaDB:      localhost:3306, user/password: devbox

EOF

trap "on_exit" EXIT

on_exit() {
  kill -HUP $pid
}

chpst -u devbox runsvdir /etc/service &
pid=$!
wait
