#!/bin/bash
set -euo pipefail

# Create ephemeral devbox user with host UID/GID so host volumes can be accessed
groupadd --gid "$DEVBOX_GID" devbox
useradd --uid "$DEVBOX_UID" --gid "$DEVBOX_GID" devbox

# Set up state directories used by various tools
install -m 750 -d /var/www/.cache -o devbox -g devbox
install -m 750 -d /var/www/.yarn  -o devbox -g devbox

# Ensure volume permissions are correct
chown --recursive devbox: /var/www/.cache

cat <<EOF
┌─────────────────────────────────┐
│ Zis is ze devbox. It boxes dev. │
└─────────────────────────────────┘
EOF

trap "on_exit" EXIT

on_exit() {
  kill -HUP $pid
}

runsvdir /etc/service &
pid=$!
wait
