version: "3.4"

services:

  apache2:
    build:
      context: ./docker
      target: devbox_apache2

    volumes:
      - $DEVBOX_PROJECTS_DIR:/var/www/projects
      - $DEVBOX_REPO_DIR/shell:/var/www/shell
      - ./config:/etc/devbox:ro
      - ./volumes/logs/apache2:/var/log/apache2
      - apache2-vhosts:/run/devbox-apache2-vhosts
      - sockets:/run/devbox-sockets

    ports:
      - 8080:80

    network_mode: host
    stop_signal: SIGHUP
    env_file: ./tmp/host.env

  php:
    build:
      context: ./docker
      target: devbox_php

    volumes:
      - $DEVBOX_PROJECTS_DIR:/var/www/projects
      - $DEVBOX_REPO_DIR/shell:/var/www/shell
      - ./volumes/logs/php:/var/log/php
      - sockets:/run/devbox-sockets

    network_mode: host
    stop_signal: SIGHUP
    stop_grace_period: 1s
    env_file: ./tmp/host.env

  mariadb:
    build:
      context: ./docker
      target: devbox_mariadb

    volumes:
      - ./volumes/data/mariadb:/var/lib/mysql
      - ./volumes/logs/mariadb:/var/log/mysql
      - sockets:/run/devbox-sockets

    ports:
      - 3036:3036

    network_mode: host
    env_file: ./tmp/host.env

volumes:
  sockets:
  apache2-vhosts:
