#!/bin/bash
install -m 755 -d /run/mysqld -o mysql -g root
chown -R mysql:root /var/lib/mysql

mysqld \
  --user=mysql \
  --init-file=/mariadb_init.sql \
  --silent-startup \
  2> >(log-prefix \! mariadb) \
  1> >(log-prefix . mariadb)
