#!/bin/bash
set -e

if [[ ! -d /var/lib/mysql/mysql ]]; then
  mysql_install_db
fi

mysqld \
  --init-file=/mariadb_init.sql \
  --silent-startup \
  2> >(log-prefix \! mariadb) \
  1> >(log-prefix . mariadb)
