#!/bin/bash
set -eu
cd /devbox/vagrant/files

# This also does an apt-get update automatically.
apt-add-repository --yes ppa:ondrej/php

apt-get upgrade --yes

php7_3_packages=(
  php7.3-fpm php7.3-xml php7.3-curl php7.3-intl php7.3-gd php7.3-imagick
  php7.3-mbstring php7.3-zip php7.3-mysql php7.3-soap
)

php5_6_packages=(
  php5.6-fpm php5.6-xml php5.6-curl php5.6-intl php5.6-gd php5.6-imagick
  php5.6-mbstring php5.6-zip php5.6-mysql php5.6-soap php5.6-mcrypt
)

apt-get install --yes --no-install-recommends \
	"${php7_3_packages[@]}" \
	"${php5_6_packages[@]}" \
	apache2 composer \
	default-mysql-client pv tree

# Apache setup
cp apache2-devbox.conf       /etc/apache2/conf-available/devbox.conf
cp apache2-devbox-vhost.conf /etc/apache2/sites-available/devbox.conf

a2enmod   --quiet proxy_fcgi setenvif rewrite
a2enconf  --quiet php7.3-fpm devbox
a2dissite --quiet 000-default
a2ensite  --quiet devbox

systemctl reload apache2

# PHP setup
for version in 5.6 7.3; do
  pool_dir=/etc/php/"$version"/fpm/pool.d

  mv "$pool_dir"/www.conf "$pool_dir"/www.conf.bak
  cp php"$version"-fpm-pool.conf "$pool_dir"/vagrant.conf

  systemctl restart php"$version"-fpm
done

# Config for system utils

cp tmux.conf   /etc/tmux.conf
cp vimrc.local /etc/vim/vimrc.local

cp ssh_known_hosts /etc/ssh/ssh_known_hosts

rm -rf /home/vagrant/.cache
ln -s /devbox/home-vagrant-cache /home/vagrant/.cache

printf "\n\n# Added by devbox provisioning script\ncd /projects\n" \
       >> /home/vagrant/.bashrc

echo "provisioning complete"
