# coding: utf-8
require_relative "devbox"

Vagrant.configure("2") do |config|
  dc = DEVBOX_CONFIG

  config.vm.define "devbox"

  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "devbox"

  config.vm.network "private_network", ip: "192.168.137.2"

  Devbox.synced_folder config, ".", "/devbox/vagrant"

  Devbox.synced_folder config, :host_webroot_dir, "/projects"
  Devbox.synced_folder config, :host_cache_dir, "/devbox/home-vagrant-cache"

  Devbox.synced_folder config,
                       Devbox.state_dir("apache2-sites"),
                       "/devbox/apache2-sites"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = dc[:cores]
    virtualbox.memory = dc[:memory]
    virtualbox.default_nic_type = "virtio" if Devbox.linux?
  end

  if Devbox.linux?
    config.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = dc[:cores]
      libvirt.memory = dc[:memory]
      libvirt.disk_bus = "virtio"
    end
  end

  config.vm.provision "shell", path: "provision"

  config.ssh.extra_args = ["-A"]

  config.trigger.after [:up, :reload] do |trigger|
    trigger.name = "Restart services that depend on host mounts"
    trigger.run_remote = {inline: "systemctl restart apache2 php7.3-fpm php5.6-fpm"}
  end
end
