#!/bin/sh
set -eu

# Set up state directories used by various tools
install -m 750 -d /var/www/.cache -o www-data -g www-data
install -m 750 -d /var/www/.yarn  -o www-data -g www-data

# Set up ephemeral directories needed by our services
install -m 755 -d /run/apache2/devbox-vhosts -o www-data -g www-data
install -m 750 -d /run/ssh-agent             -o www-data -g www-data
install -m 755 -d /run/mysqld                -o mysql    -g root
install -m 755 -d /run/php

# Ensure volume permissions are correct as changes to the build
# process may result in UIDs changing
chown -R mysql:root /var/lib/mysql
chown -R www-data:  /var/www/.cache

stop_all() {
  for service in /etc/service/*; do
    sv stop "$service"
  done
}

trap stop_all TERM

runsvdir /etc/service &
wait
