#!/bin/bash
#
# install -- setup script for the devbox image
#
set -eu

# Skip all interactive package configuration
export DEBIAN_FRONTEND=noninteractive

packages=(
  runit
  apache2
  mariadb-server
  composer
  openssh-client
  git
  libyaml-0-2  # required for mod_vhost_devbox
  ruby  # required for mailcatcher

  # ppa:ondrej/php
  php7.3-fpm php7.3-xml php7.3-curl php7.3-intl php7.3-gd
  php7.3-imagick php7.3-mbstring php7.3-zip php7.3-mysql php7.3-soap
  php7.3-yaml

  php5.6-fpm php5.6-xml php5.6-curl php5.6-intl php5.6-gd
  php5.6-imagick php5.6-mbstring php5.6-zip php5.6-mysql php5.6-soap
  php5.6-mcrypt

  # nodesource & yarn
  nodejs yarn
)

# These packages can be removed before the image is finalized
packages_temporary=(
  # build requirements for mailcatcher
  build-essential ruby-dev libsqlite3-dev

  # build requirements for mod_vhost_devbox
  apache2-dev libyaml-dev
)

# -- Add third-party software sources -------------------------------------------
# (signing keys are in docker/files.apt-pre/etc/apt/trusted.gpg.d)

apt-get update --quiet=2
apt-get install --quiet=2 --no-install-recommends \
	software-properties-common apt-transport-https gnupg

echo 'deb https://deb.nodesource.com/node_12.x bionic main' \
     > /etc/apt/sources.list.d/nodesource.list

echo 'deb https://dl.yarnpkg.com/debian/ stable main' \
     > /etc/apt/sources.list.d/yarn.list

# This updates the package lists, no additional apt update is needed
apt-add-repository --yes ppa:ondrej/php

# -- Install upgrades and packages ----------------------------------------------

apt-get upgrade --quiet=2
apt-get install --quiet=2 --no-install-recommends \
	"${packages[@]}" "${packages_temporary[@]}"

gem install --no-document mailcatcher

make -C /tmp/mod_vhost_devbox install

# -- Cleanup --------------------------------------------------------------------

apt-get purge --quiet=2 "${packages_temporary[@]}"
apt-get autoremove --quiet=2 --purge

rm -rf /var/lib/apt/lists/* /tmp/mod_vhost_devbox
