#!/usr/bin/env bash
set -euo pipefail

if [[ $# != 1 ]]; then
  >&2 echo "invalid number of arguments: $#"
  >&2 echo "usage: $0 PHP_VERSION"
  exit 1
fi

install -m 755 -d /run/php

version="$1"

"php-fpm$version" \
  --nodaemonize \
  --fpm-config "/etc/php/$version/fpm/php-fpm.conf" \
  2> >(log-prefix \! php-fpm$version) \
  1> >(log-prefix . php-fpm$version)
