general:
  projects_root: /var/www/projects

php:
  default_version: "7.4"
  versions:
    "8.0":
      socket: /run/php/php8.0-fpm.sock
      binary: /usr/bin/php8.0
    "7.4":
      socket: /run/php/php7.4-fpm.sock
      binary: /usr/bin/php7.4
    "7.3":
      socket: /run/php/php7.3-fpm.sock
      binary: /usr/bin/php7.3
    "5.6":
      socket: /run/php/php5.6-fpm.sock
      binary: /usr/bin/php5.6

autoconf:
  apache2:
    vhost_directory: /run/apache2/devbox-vhosts
    reload_command: apachectl -k graceful
