#!/bin/bash
set -eu

# these should stay in the final image
packages=(
  supervisor apache2 mariadb-server composer

  php7.3-fpm php7.3-xml php7.3-curl php7.3-intl php7.3-gd
  php7.3-imagick php7.3-mbstring php7.3-zip php7.3-mysql php7.3-soap
  php7.3-yaml

  php5.6-fpm php5.6-xml php5.6-curl php5.6-intl php5.6-gd
  php5.6-imagick php5.6-mbstring php5.6-zip php5.6-mysql php5.6-soap
  php5.6-mcrypt

  # runtime requirement for mod_vhost_devbox
  libyaml-0-2

  # runtime requirement for mailcatcher
  ruby
)

# these should be removed after they're no longer needed
packages_build_deps=(
  # build requirements for mailcatcher
  build-essential ruby-dev libsqlite3-dev
)

# skip all interactive package configuration
export DEBIAN_FRONTEND=noninteractive

apt-get update -qq
apt-get install -qq --no-install-recommends software-properties-common
apt-add-repository --yes ppa:ondrej/php

apt-get install -qq --no-install-recommends \
	"${packages[@]}" "${packages_build_deps[@]}"

gem install mailcatcher

# clean up anything that isn't needed in the final image
apt-get purge -qq "${packages_build_deps[@]}"
apt-get autoremove -qq --purge
rm -rf /var/lib/apt/lists/*
