#!/usr/bin/env bash
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

cmd="$1"
shift

case "$cmd" in
  run)
    echo "running build script: $1"
    source "$1"
    ;;

  update)
    apt-get update --quiet=2
    ;;

  upgrade)
    apt-get upgrade --quiet=2 --yes
    ;;

  install)
    apt-get install --quiet=2 --no-install-recommends --yes "$@"
    ;;

  remove)
    apt-get remove --quiet=2 --yes "$@"
    ;;

  shrink)
    echo "shrinking image..."
    apt-get clean
    rm -rf /var/lib/apt/lists/*
    ;;

  *)
    >&2 echo "$0: invalid command: $cmd"
    return 1
esac
